import { useEffect, useMemo, useState } from "react";
import Icon from "../components/Icon.jsx";
import MediaCollection from "../components/MediaCollection.jsx";
import FilterToolbar from "../components/FilterToolbar.jsx";
import { getSmartHubMedia, resolveAPIURL } from "../lib/api.js";

export default function SmartHubPage({ slug, onOpenMedia }) {
  const [data, setData] = useState(null); const [sort, setSort] = useState("newest"); const [query, setQuery] = useState("");
  useEffect(() => { let alive=true; getSmartHubMedia(slug,{sort:sort === "newest" ? "" : sort,limit:1000}).then((x)=>alive&&setData(x)).catch(()=>alive&&setData({hub:null,items:[],total:0})); return()=>{alive=false}; },[slug,sort]);
  const items = useMemo(() => (data?.items||[]).map((x)=>({id:x.id,titleAr:x.title_ar,titleEn:x.title_en,type:x.type,plot:x.plot_ar||x.plot_en,year:x.release_year,rating:x.rating,posterPath:x.poster_path,bannerPath:x.banner_path,status:x.status,seasonCount:x.season_count,tmdbSeasonCount:x.tmdb_season_count,bestResolution:x.best_resolution,totalSize:x.total_size,hasArabicAudio:x.has_arabic_audio,hasArabicSubtitles:x.has_arabic_subtitles,genres:x.genres||[]})).filter((x)=>!query.trim() || `${x.titleAr} ${x.titleEn} ${x.plot}`.toLowerCase().includes(query.toLowerCase())),[data,query]);
  const hub=data?.hub; if (!data) return <div className="min-h-[300px] animate-pulse rounded-2xl bg-white/5" />; if (!hub) return <div className="py-20 text-center text-white/60">لم يتم العثور على هذا المحور.</div>;
  const artwork=resolveAPIURL(hub.artwork_path)||"/nexora-library-backdrop.PNG";
  return <div className="space-y-7 pb-16" dir="rtl"><section className="relative min-h-[300px] overflow-hidden rounded-2xl border border-white/10 bg-[#12101d] sm:min-h-[360px]"><img src={artwork} alt="" className="absolute inset-0 h-full w-full object-cover" style={{objectPosition:hub.artwork_position||"center center"}}/><div className="absolute inset-0 bg-gradient-to-l from-black/90 via-black/60 to-black/10"/><div className="relative flex min-h-[300px] max-w-2xl flex-col justify-end gap-4 p-6 sm:min-h-[360px] sm:p-9"><span className="flex h-11 w-11 items-center justify-center rounded-xl border border-white/25 bg-white/10 text-white backdrop-blur"><Icon name={hub.icon||"spark"}/></span><div><h1 className="text-3xl font-black text-white sm:text-4xl">{hub.title_ar||hub.title_en}</h1>{hub.title_ar&&hub.title_en&&<p className="mt-1 text-sm font-semibold text-white/60" dir="ltr">{hub.title_en}</p>}<p className="mt-3 max-w-xl text-sm leading-7 text-white/80">{hub.description_ar||hub.description_en||"مختارات من مكتبتك المحلية."}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-lg border border-white/15 bg-black/25 px-3 py-1.5 text-xs font-bold text-white">{data.total} عمل</span><span className="rounded-lg border border-white/15 bg-black/25 px-3 py-1.5 text-xs font-bold text-white">مرتب حسب بيانات المكتبة</span></div></div></section><FilterToolbar showOriginFilter={false} activeSort={sort} onSelectSort={setSort} activeGenre="all" onSelectGenre={()=>{}} searchQuery={query} onSearchChange={setQuery} resultCount={items.length}/><MediaCollection items={items} onOpenMedia={onOpenMedia} emptyMessage="لا توجد أعمال تطابق هذا المحور حاليًا." /></div>;
}
